set nocompatible              " be iMproved, required
filetype off                  " required

execute pathogen#infect()
se rtp+=~/.vim/bundlet/Vundle.vim
call vundle#begin()
Plugin 'ervandew/supertab'
Plugin 'tpope/vim-commentary'
call vundle#end()            " required
filetype plugin indent on    " required

filetype plugin on

so ~/linux_config/vim/src/core/base/.vimrc

" TO install: in vim, PluginInstall
let g:syntastic_python_checkers = ["flake8"]
let g:syntastic_python_flake8_exe = "python3 -m flake8"
let python_highlight_all=1

silent! colorscheme jellybeans
