set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'posva/vim-vue'
Plugin 'ervandew/supertab'
Plugin 'tpope/vim-commentary'
Plugin 'davidhalter/jedi-vim'
Plugin 'pangloss/vim-javascript'
Plugin 'leafgarland/typescript-vim'
call vundle#end()            " required
filetype plugin indent on    " required

filetype plugin on

" so ~/linux_config/vim/src/jedi/.vimrc
" so ~/linux_config/src/core/base/.vimrc
" so ~/linux_config/vim/src/javascript/.vimrc
" so ~/linux_config/src/core/filetypes/.vimrc

" TO install: in vim, PluginInstall
let g:syntastic_python_checkers = ["flake8"]
let g:syntastic_python_flake8_exe = "python3 -m flake8"
let python_highlight_all=1

silent! colorscheme jellybeans
